server:
  port: ${SERVER_PORT:9000}
  servlet:
    context-path: /
  error:
    path: /error
    whitelabel:
      enabled: false
  ssl:
    key-store-type: ${SSL_KEY_STORE_TYPE:PKCS12}
    key-store: ${SSL_KEY_STORE:}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:}
    key-alias: ${SSL_KEY_ALIAS:}
    enabled: ${SSL_ENABLED:false}

spring:
  jmx:
    enabled: true
    default_domain: Kafdrop
  jackson:
    deserialization:
      fail_on_unknown_properties: false
      read_unknown_enum_values_as_null: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: "*"
  server:
    port: 9000

kafdrop.monitor:
  clientId: Kafdrop

kafka:
  brokerConnect: "${KAFKA_BROKER_CONNECT:boot-81iy9xcc.c1.kafka-serverless.ap-south-1.amazonaws.com:9098}"
  saslMechanism: "AWS_MSK_IAM"
  securityProtocol: "SASL_SSL"
  truststoreFile: "${KAFKA_TRUSTSTORE_FILE:kafka.truststore.jks}"
  propertiesFile : "${KAFKA_PROPERTIES_FILE:kafka.properties}"
  keystoreFile: "${KAFKA_KEYSTORE_FILE:kafka.keystore.jks}"
  iamEnabled: "${KAFKA_IAM_ENABLED:true}"
  saslJaasConfig: "${KAFKA_SASL_JAAS_CONFIG:software.amazon.msk.auth.iam.IAMLoginModule required;}"
  saslClientCallback: "${KAFKA_SASL_CLIENT_CALLBACK:software.amazon.msk.auth.iam.IAMClientCallbackHandler}"

schemaRegistry:
  glue:
    registryName: "${GLUE_SCHEMA_REGISTRY_NAME:ind-dev1-glue-schema-registry}"
    region: "${GLUE_REGION:ap-south-1}"
